use std::fs;
use std::path::Path;

fn main() {
    // The bundled CLI sidecar is generated by `npm run prepare:sidecar` and
    // untracked, but tauri_build validates the `resources: ["bin/*"]` glob on
    // every compile — including plain cargo check/clippy/test on a fresh
    // clone, which never run Tauri's before*Command hooks. Seed a zero-byte
    // placeholder so those builds pass; prepare-sidecar.mjs treats an empty
    // file as missing, so tauri dev/build still produce the real CLI.
    let name = if cfg!(windows) {
        "gpt-image-2-skill.exe"
    } else {
        "gpt-image-2-skill"
    };
    let placeholder = Path::new("bin").join(name);
    if !placeholder.exists() {
        let _ = fs::create_dir_all("bin");
        let _ = fs::write(&placeholder, b"");
    }
    tauri_build::build();
}
