#![allow(unused_imports)]

use std::fs;
use std::io::{self, BufRead, BufReader, Read, Write};
use std::net::{IpAddr, Ipv4Addr, SocketAddr, TcpStream, ToSocketAddrs};
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use std::{collections::BTreeMap, process::Command, sync::mpsc, thread};

use base64::Engine;
use base64::engine::general_purpose::{STANDARD, URL_SAFE_NO_PAD};
use chrono::Utc;
use clap::{ArgAction, Args, Parser, Subcommand, ValueEnum};
use hmac::{Hmac, Mac};
use lettre::message::{Mailbox, header::ContentType};
use lettre::transport::smtp::authentication::Credentials;
use lettre::{Message, SmtpTransport, Transport};
use reqwest::StatusCode;
use reqwest::blocking::multipart::{Form, Part};
use reqwest::blocking::{Client, Response};
use reqwest::header::{ACCEPT, AUTHORIZATION, CONTENT_TYPE, HeaderMap, HeaderName, HeaderValue};
use rusqlite::types::Value as SqlValue;
use rusqlite::{Connection, Row, params, params_from_iter};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value, json};
use sha2::{Digest, Sha256};
use ssh2::Session;
use url::Url;

mod auth;
mod auth_types;
mod cli_types;
mod config_commands;
mod config_io;
mod config_types;
mod constants;
mod credentials;
mod errors;
mod history_commands;
mod history_db;
mod history_list;
mod image_commands;
mod image_requests;
mod json_events;
mod network_safety;
mod notifications;
mod paths;
mod provider_selection;
mod provider_types;
mod request_commands;
mod request_payloads;
mod runtime_image_args;
mod runtime_request_types;
mod storage_config;
mod storage_upload_attempts;
mod storage_upload_common;
mod storage_upload_local_http;
mod storage_upload_remote;
mod storage_upload_runner;
mod storage_upload_s3;
mod transparent;
mod util;

pub use auth::*;
pub(crate) use auth::*;
pub use auth_types::*;
pub(crate) use auth_types::*;
pub use cli_types::*;
pub(crate) use cli_types::*;
pub use config_commands::*;
pub(crate) use config_commands::*;
pub use config_io::*;
pub(crate) use config_io::*;
pub use config_types::*;
pub(crate) use config_types::*;
pub use constants::*;
pub(crate) use constants::*;
pub use credentials::*;
pub(crate) use credentials::*;
pub use errors::*;
pub(crate) use errors::*;
pub use history_commands::*;
pub(crate) use history_commands::*;
pub use history_db::*;
pub(crate) use history_db::*;
pub use history_list::*;
pub(crate) use history_list::*;
pub use image_commands::*;
pub(crate) use image_commands::*;
pub use image_requests::*;
pub(crate) use image_requests::*;
pub use json_events::*;
pub(crate) use json_events::*;
pub use network_safety::*;
pub(crate) use network_safety::*;
pub use notifications::*;
pub(crate) use notifications::*;
pub use paths::*;
pub(crate) use paths::*;
pub use provider_selection::*;
pub(crate) use provider_selection::*;
pub use provider_types::*;
pub(crate) use provider_types::*;
pub use request_commands::*;
pub(crate) use request_commands::*;
pub use request_payloads::*;
pub(crate) use request_payloads::*;
pub use runtime_image_args::*;
pub(crate) use runtime_image_args::*;
pub use runtime_request_types::*;
pub(crate) use runtime_request_types::*;
pub use storage_config::*;
pub(crate) use storage_config::*;
pub use storage_upload_attempts::*;
pub(crate) use storage_upload_attempts::*;
pub use storage_upload_common::*;
pub(crate) use storage_upload_common::*;
pub use storage_upload_local_http::*;
pub(crate) use storage_upload_local_http::*;
pub use storage_upload_remote::*;
pub(crate) use storage_upload_remote::*;
pub use storage_upload_runner::*;
pub(crate) use storage_upload_runner::*;
pub use storage_upload_s3::*;
pub(crate) use storage_upload_s3::*;
pub use util::*;
pub(crate) use util::*;

#[cfg(test)]
mod tests;
